export const SUBJECTS_ACTION_TYPES = {
  FETCH_SUBJECTS_START: 'FETCH_SUBJECTS_START',
  FETCH_SUBJECTS_SUCCESS: 'FETCH_SUBJECTS_SUCCESS',
  FETCH_SUBJECTS_FAILED: 'FETCH_SUBJECTS_FAILED',

  SEND_SUBJECTS: 'SEND_SUBJECTS',
  UPDATE_PODGROUP: 'UPDATE_PODGROUP',
  UPDATE_SUBJECT: 'UPDATE_SUBJECT',

  ADD_PODGROUP: 'ADD_PODGROUP',
  REMOVE_PODGROUP: 'REMOVE_PODGROUP',
};